### ISSUE TITLE
收不到邮件

### ISSUE THREAD

**Issue by XShandow** [zhaojun1998/Valine-Admin#10]
![image](https://user-images.githubusercontent.com/15667872/44066373-91347cb4-9fa2-11e8-96d6-219e1ad0f2d9.png)
为什么我设置了，但是收不到评论的邮件呢？
QQ邮箱也开启SMTP了，

**Comment by zhaojun1998** [comment]
注意看 README 啊。
配置了 `SMTP_SERVICE` 为 `QQ` 后，只需要配置 `SMTP_USER` 为邮箱，密码为 QQ 邮箱授权码即可。

`SMTP_HOST` 与 `SMTP_PORT` 是为不包括在 `SMTP_SERVICE` 里的邮箱配置的。

另外你收不到评论的邮件，请贴出 **云引擎->应用日志** 的日志内容。

**Comment by zhaojun1998** [comment]
@XShandow

**Comment by XShandow** [comment]
这条评论没有 @ 任何人
STDOUT web1 09:36:10
  responseCode: 535,
STDOUT web1 09:36:10
{ Error: Invalid login: 535 Error: ÇëÊ¹ÓÃÊÚÈ¨ÂëµÇÂ¼¡£ÏêÇéÇë¿´: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
STDOUT web1 09:36:10
    at SMTPConnection._formatError (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
STDOUT web1 09:36:10
    at SMTPConnection._actionAUTHComplete (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:1335:34)
STDOUT web1 09:36:10
    at SMTPConnection._responseActions.push.str (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:366:26)
STDOUT web1 09:36:10
    at SMTPConnection._processResponse (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)
STDOUT web1 09:36:10
    at SMTPConnection._onData (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)
STDOUT web1 09:36:10
    at TLSSocket._socket.on.chunk (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:510:47)
STDOUT web1 09:36:10
    at emitOne (events.js:96:13)
STDOUT web1 09:36:10
    at TLSSocket.emit (events.js:188:7)
STDOUT web1 09:36:10
    at readableAddChunk (_stream_readable.js:176:18)
STDOUT web1 09:36:10
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
STDOUT web1 09:36:10
  code: 'EAUTH',
STDOUT web1 09:36:10
  response: '535 Error: ÇëÊ¹ÓÃÊÚÈ¨ÂëµÇÂ¼¡£ÏêÇéÇë¿´: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256',
STDOUT web1 09:36:10
  command: 'AUTH PLAIN' }

**Comment by XShandow** [comment]
刚开始用的另外一个valine-admin,还看了你的日志，配置的有点乱了。
![image](https://user-images.githubusercontent.com/15667872/44067017-f992b8ea-9fa5-11e8-846e-876e55a1ce22.png)
这是最后的配置，PASS是填的授权码

**Comment by zhaojun1998** [comment]
将 `SMTP_HOST` 与 `SMTP_PORT` 删除，然后重启容器，在测试下。

注意：QQ 的 `SMTP_PASS`  不是 qq 登陆密码，而是授权码。

**Comment by zhaojun1998** [comment]
@XShandow

**Comment by XShandow** [comment]
这条评论没有 @ 任何人
STDOUT web1 09:42:47
{ Error: connect ECONNREFUSED 127.0.0.1:465
STDOUT web1 09:42:47
    at Object.exports._errnoException (util.js:1020:11)
STDOUT web1 09:42:47
    at exports._exceptionWithHostPort (util.js:1043:20)
STDOUT web1 09:42:47
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
STDOUT web1 09:42:47
  code: 'ECONNECTION',
STDOUT web1 09:42:47
  errno: 'ECONNREFUSED',
STDOUT web1 09:42:47
  syscall: 'connect',
STDOUT web1 09:42:47
  address: '127.0.0.1',
STDOUT web1 09:42:47
  port: 465,
STDOUT web1 09:42:47
  command: 'CONN' }

**Comment by XShandow** [comment]
![image](https://user-images.githubusercontent.com/15667872/44067142-8a5f9a82-9fa6-11e8-8c91-3f0538c69757.png)

**Comment by XShandow** [comment]
![image](https://user-images.githubusercontent.com/15667872/44067172-b8c9af98-9fa6-11e8-8ab8-6718710d123f.png)

**Comment by zhaojun1998** [comment]
@XShandow 方便加 QQ 么。可以的话 QQ 给你解决。

**Comment by XShandow** [comment]
76731121

**Comment by zhaojun1998** [comment]
已解决，原因是配置文件搞错。
