### ISSUE TITLE
SMTP_SERVICE 选择 Gmail 时发生错误

### ISSUE THREAD

**Issue by mofiter** [zhaojun1998/Valine-Admin#14]
错误日志为：
    at SMTPConnection._formatError (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
{ Error: Connection timeout
    at SMTPConnection._onError (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:579:20)
    at Timeout._connectionTimeout.setTimeout (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:261:18)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) code: 'ETIMEDOUT', command: 'CONN' }
麻烦帮忙看下是什么问题

**Comment by zhaojun1998** [comment]
@mofiter 请截图你的环境变量配置，注意密码打码，如使用的是 QQ 或 163 邮箱，请确定密码是授权码，而不是登陆密码。

**Comment by zhaojun1998** [comment]
@mofiter 嗯，不客气，谢谢支持。
