### ISSUE TITLE
无法收到邮件

### ISSUE THREAD

**Issue by JadeVane** [zhaojun1998/Valine-Admin#17]
已经按照readme设置好leancloud和定时任务，并且在做出更改后已重启实例，可是无法收到邮件。

应用日志
```
STDOUT web1 13:19:15  正在创建新实例 ...
STDOUT web1 13:19:21  正在启动新实例 ...
STDOUT web1 13:19:22  
STDOUT web1 13:19:22  > node-js-getting-started@1.0.0 start /home/leanengine/app
STDOUT web1 13:19:22  > node server.js
STDOUT web1 13:19:22  
STDOUT web1 13:19:24  Node app is running on port: 3000
STDOUT web1 13:19:24  实例启动成功：{"runtime":"nodejs-v6.14.4","version":"3.3.2"}
STDOUT web1 13:19:55    responseCode: 535,
STDOUT web1 13:19:55  这条评论没有 @ 任何人
STDOUT web1 13:19:55  { Error: Invalid login: 535 Error: authentication failed
STDOUT web1 13:19:55      at SMTPConnection._actionAUTHComplete (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:1335:34)
STDOUT web1 13:19:55      at SMTPConnection._responseActions.push.str (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:366:26)
STDOUT web1 13:19:55      at SMTPConnection._processResponse (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)
STDOUT web1 13:19:55      at SMTPConnection._onData (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)
STDOUT web1 13:19:55      at TLSSocket._socket.on.chunk (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:510:47)
STDOUT web1 13:19:55      at emitOne (events.js:96:13)
STDOUT web1 13:19:55      at readableAddChunk (_stream_readable.js:176:18)
STDOUT web1 13:19:55      at TLSSocket.Readable.push (_stream_readable.js:134:10)
STDOUT web1 13:19:55    response: '535 Error: authentication failed',
STDOUT web1 13:19:55    command: 'AUTH PLAIN' }
STDOUT web1 13:20:27    code: 'EAUTH',
STDOUT web1 13:20:27  { Error: Invalid login: 535 Error: authentication failed
STDOUT web1 13:20:27      at SMTPConnection._formatError (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
STDOUT web1 13:20:27      at SMTPConnection._actionAUTHComplete (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:1335:34)
STDOUT web1 13:20:27      at SMTPConnection._responseActions.push.str (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:366:26)
STDOUT web1 13:20:27      at SMTPConnection._processResponse (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)
STDOUT web1 13:20:27      at SMTPConnection._onData (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)
STDOUT web1 13:20:27      at TLSSocket._socket.on.chunk (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:510:47)
STDOUT web1 13:20:27      at TLSSocket.emit (events.js:188:7)
STDOUT web1 13:20:27      at readableAddChunk (_stream_readable.js:176:18)
STDOUT web1 13:20:27      at TLSSocket.Readable.push (_stream_readable.js:134:10)
STDOUT web1 13:20:27    code: 'EAUTH',
STDOUT web1 13:20:27    response: '535 Error: authentication failed',
STDOUT web1 13:20:27    responseCode: 535,
STDOUT web1 13:20:27    command: 'AUTH PLAIN' }
STDOUT web1 13:20:27  { Error: Invalid login: 535 Error: authentication failed
STDOUT web1 13:20:27      at SMTPConnection._formatError (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:606:19)
STDOUT web1 13:20:27      at SMTPConnection._actionAUTHComplete (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:1335:34)
STDOUT web1 13:20:27      at SMTPConnection._responseActions.push.str (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:366:26)
STDOUT web1 13:20:27      at SMTPConnection._processResponse (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:762:20)
STDOUT web1 13:20:27      at SMTPConnection._onData (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:558:14)
STDOUT web1 13:20:27      at TLSSocket._socket.on.chunk (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:510:47)
STDOUT web1 13:20:27      at emitOne (events.js:96:13)
STDOUT web1 13:20:27      at TLSSocket.emit (events.js:188:7)
STDOUT web1 13:20:27      at readableAddChunk (_stream_readable.js:176:18)
STDOUT web1 13:20:27      at TLSSocket.Readable.push (_stream_readable.js:134:10)
STDOUT web1 13:20:27    response: '535 Error: authentication failed',
STDOUT web1 13:20:27    responseCode: 535,
STDOUT web1 13:20:27    command: 'AUTH PLAIN' }
```

配置
![default](https://user-images.githubusercontent.com/34258753/46271306-94ee5a80-c57e-11e8-8609-b6706cc0df22.PNG)

使用网易企业邮箱， 不知这样配置是否有误？

**Comment by JadeVane** [comment]
评论所留邮箱并不是TO_MAIL或者SMTP_USER所用邮箱

**Comment by JadeVane** [comment]
已解决，需要设置对应的`SMTP_HOST`和`SMTP_PORT`参数，然后删除`SMTP_SERVICE`参数即可
