### ISSUE TITLE
报错{ Error: connect ECONNREFUSED 127.0.0.1:465

### ISSUE THREAD

**Issue by AlliotTech** [zhaojun1998/Valine-Admin#18]
这条评论没有 @ 任何人
STDOUT web1 10:01:32
{ Error: connect ECONNREFUSED 127.0.0.1:465
STDOUT web1 10:01:32
    at Object.exports._errnoException (util.js:1020:11)
STDOUT web1 10:01:32
    at exports._exceptionWithHostPort (util.js:1043:20)
STDOUT web1 10:01:32
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
STDOUT web1 10:01:32
  code: 'ECONNECTION',
STDOUT web1 10:01:32
  errno: 'ECONNREFUSED',
STDOUT web1 10:01:32
  syscall: 'connect',
STDOUT web1 10:01:32
  address: '127.0.0.1',
STDOUT web1 10:01:32
  port: 465,
STDOUT web1 10:01:32
  command: 'CONN' }

**Comment by AlliotTech** [comment]
SMTP_PASS 设置的是授权码 
SMTP_SERVICE “”QQ“ ”

**Comment by zhaojun1998** [comment]
配置截图下吧，授权码你打码就行了。

**Comment by AlliotTech** [comment]
![qq 20181004101235](https://user-images.githubusercontent.com/24980252/46449349-2697db00-c7be-11e8-9a62-d4ce782e5ab5.png)

**Comment by AlliotTech** [comment]
valine:
  enable: true
  appid:  1111111
  appkey:  11111111111
  notify: true # mail notifier , https://github.com/xCss/Valine/wiki
主题配置文件中的notify是打开的

**Comment by AlliotTech** [comment]
![image](https://user-images.githubusercontent.com/24980252/46449421-84c4be00-c7be-11e8-9978-2f0be43696fe.png)

**Comment by zhaojun1998** [comment]
@AlliotTech  重启容器了么
